baseurl = "https://www.thephantomninja.com/"
title = "The Phantom Ninja"
languageCode = "en-us"
disqusShortname = "thephantomninja" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10
paginatePath = "page"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[author]
    name = "phantom ninja"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "The Phantom Ninja blog covers topics across personal finance, mobile applications and technology in general."
    defaultKeywords = ""

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0d"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = ""

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "#blog".
    home = "#blog"

    # Metadata used to drive integrations.
#   googleAuthorship = "Your Google+ profile ID"
    googleAnalytics = "UA-71327768-1"
    gravatarHash = "a53aa2fd3d30698ac8b9a61065885f14s"

    # Sidebar social links, these must be full URLs.
    github = ""
    bitbucket = ""
    stackOverflow = ""
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link
#    flattr = ""  # populate with your flattr uid
